### ISSUE TITLE
Connection error while Using the Curator Command

### ISSUE THREAD

**Issue by balubollam** [dapicard/elastic-curator#4]
Hi

I have installed the curator and PIP.
after that i have used curator,curator show command ..They are working fine.
But when i try to user other commans like
curator show --all-indices
iam getting: "INFO Job starting:show indices
ERROR Connection failure"

And one more query .. is it compulsory to install the APT and YEM repository?...
wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
When i use this I am getting Error that
sudo:apt-key is not a command

Can u please help me in this.Iam new to this Concept

Thanks & Regards
Balaji

**Comment by dapicard** [comment]
Hi,

I think you are talking about https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html ; this is not the same product as elastic-sweeper.

Regards,
